USE Hotel;
GO

<<<<<<< HEAD

--ROOM TYPES 1-3
INSERT INTO Room_type VALUES
('Enkelrum',1,0), ('Dubbelrum',2,1), ('Svit',2,2);


--ROOMS 1-400
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (3, 0);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (3, 2);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (1, 2);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (2, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
insert into Room (room_type_id, extra_bed) values (2, 0);
insert into Room (room_type_id, extra_bed) values (1, 0);
insert into Room (room_type_id, extra_bed) values (1, 1);
insert into Room (room_type_id, extra_bed) values (3, 1);
GO

UPDATE Room
SET extra_bed=0
WHERE room_type_id = 1
GO


--EMPLOYEES
=======
-- Anställda
>>>>>>> 44e88601db739ee6fc47d73aa7436e92828b0e5b
insert into Employees (first_name, last_name, position) values ('Kim', 'Grellier', 'Reception');
insert into Employees (first_name, last_name, position) values ('Susana', 'Petrus', 'Booking manager');
insert into Employees (first_name, last_name, position) values ('Kiersten', 'Gravet', 'Reception');
insert into Employees (first_name, last_name, position) values ('Tonie', 'Pochin', 'Reception');
insert into Employees (first_name, last_name, position) values ('Andie', 'Charlon', 'Reception');
insert into Employees (first_name, last_name, position) values ('Claudian', 'Daingerfield', 'Reception');
insert into Employees (first_name, last_name, position) values ('Silvia', 'Eathorne', 'Reception');
insert into Employees (first_name, last_name, position) values ('Delmore', 'Toffoloni', 'Reception');
insert into Employees (first_name, last_name, position) values ('Aubrey', 'Willey', 'Reception');
insert into Employees (first_name, last_name, position) values ('Constantin', 'Moffat', 'Reception');
<<<<<<< HEAD
GO

--CUSTOMERS
=======

-- Gäster
>>>>>>> 44e88601db739ee6fc47d73aa7436e92828b0e5b
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Lane', 'Bakes', 'lbakes0@aboutads.info', '837-379-8776', '80 Reindahl Place', 'Singaparna', null, 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Marty', 'Ovanesian', 'movanesian1@eventbrite.com', '210-102-5720', '3 Westerfield Court', 'Song', '54120', 'Thailand');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Barbra', 'Rothery', 'brothery2@businessweek.com', '587-509-8096', '14 Haas Junction', 'Longtian', null, 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Grove', 'Boynes', 'gboynes3@wikispaces.com', '603-592-6012', '12 Northwestern Way', 'Mozhga', '445560', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Merl', 'Darrow', 'mdarrow4@sina.com.cn', '148-728-7499', '97 Sutteridge Drive', 'Sanlidian', null, 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Bartholomeo', 'McAllister', 'bmcallister5@hugedomains.com', '515-427-5827', '1 Blue Bill Park Lane', 'Jinxiu', null, 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Lem', 'Gurney', 'lgurney6@networkadvertising.org', '923-596-6301', '45050 Loftsgordon Point', 'Usab', '6127', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Shanda', 'Cubbit', 'scubbit7@bloomberg.com', '667-243-8901', '1 Birchwood Park', 'Dong Charoen', '66210', 'Thailand');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Roxanna', 'Shury', 'rshury8@examiner.com', '739-915-2202', '4 Crescent Oaks Plaza', 'Devin', '4815', 'Bulgaria');
insert into Customer (first_name, last_name, email, phone_number, street_address, city, postal_code, country) values ('Anastasie', 'Sabatini', 'asabatini9@toplist.cz', '905-889-2959', '2333 Holmberg Pass', 'Volokonovka', '457151', 'Russia');
<<<<<<< HEAD
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Dori', 'Ofen', 'dofen0@mozilla.com', '+380 392 990 9688', '5100 Moose Terrace', null, 'Piskivka', 'Ukraine');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Cynthea', 'Whenham', 'cwhenham1@usatoday.com', '+7 478 529 8299', '57 Fairfield Way', '140225', 'Konobeyevo', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Vick', 'Thorley', 'vthorley2@bbb.org', '+212 517 996 9483', '4 International Street', null, 'Mhamid', 'Morocco');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Aylmer', 'Stailey', 'astailey3@list-manage.com', '+86 219 958 8439', '18732 American Ash Way', null, 'Fenggao', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Dael', 'Bracknall', 'dbracknall4@jiathis.com', '+63 810 816 3005', '801 Little Fleur Road', '4516', 'Nangalisan', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Janice', 'Headings', 'jheadings5@blogs.com', '+420 598 378 8039', '18894 Utah Road', '330 16', 'Všeruby', 'Czech Republic');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Roosevelt', 'Hillum', 'rhillum6@devhub.com', '+62 580 379 6870', '577 Gina Road', null, 'Dorupare', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Mikey', 'Banks', 'mbanks7@ted.com', '+55 493 383 7620', '82 Crownhardt Hill', '15775-000', 'Santa Fé do Sul', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Lanny', 'Bellow', 'lbellow8@newyorker.com', '+234 286 852 9117', '707 Menomonie Parkway', null, 'Oguta', 'Nigeria');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Katherine', 'Whaley', 'kwhaley9@tripod.com', '+212 312 968 3575', '09 1st Place', null, 'Ghouazi', 'Morocco');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Esmeralda', 'Frisby', 'efrisbya@ca.gov', '+86 521 351 5730', '7 Blaine Place', null, 'Huanghe', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ellsworth', 'Lindenblatt', 'elindenblattb@eepurl.com', '+84 163 661 7685', '04334 Corscot Park', null, 'Phu Loc', 'Vietnam');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Roma', 'Dorrell', 'rdorrellc@nasa.gov', '+86 662 879 7037', '095 Coolidge Crossing', null, 'Xinhuang', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Myrle', 'Longhurst', 'mlonghurstd@amazon.de', '+63 455 706 1983', '81 Cottonwood Road', '9004', 'Claveria', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Alano', 'Agron', 'aagrone@wp.com', '+63 334 781 1186', '0647 Waywood Way', '5034', 'Binabaan', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Sully', 'Stuchberry', 'sstuchberryf@google.com.au', '+98 970 214 9644', '8091 Melby Alley', null, 'Dārān', 'Iran');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Wenona', 'Ourtic', 'wourticg@phoca.cz', '+86 301 793 4838', '6414 Maryland Lane', null, 'Lianghu', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Waldemar', 'Widocks', 'wwidocksh@rediff.com', '+63 194 364 9859', '24654 Debra Place', '1109', 'Casisang', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Bealle', 'Ficken', 'bfickeni@hugedomains.com', '+595 918 562 9103', '72593 Graceland Trail', null, 'Nueva Italia', 'Paraguay');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Roda', 'Dovermann', 'rdovermannj@spiegel.de', '+963 401 611 5777', '36 Kensington Hill', null, '‘Ayn al Bayḑā', 'Syria');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Gill', 'Bumphrey', 'gbumphreyk@virginia.edu', '+86 505 427 6234', '74 Tony Circle', null, 'Guanghai', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Roxane', 'Lavender', 'rlavenderl@themeforest.net', '+685 765 273 4018', '638 Chive Junction', null, 'Faleula', 'Samoa');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Lee', 'Grebbin', 'lgrebbinm@ycombinator.com', '+62 736 896 8037', '58354 Larry Plaza', null, 'Enrekang', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Terri', 'Daouse', 'tdaousen@instagram.com', '+86 382 126 1890', '51035 Reindahl Crossing', null, 'Lian’an', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Kattie', 'Godball', 'kgodballo@jimdo.com', '+86 115 924 0833', '2 Melrose Center', null, 'Jindu', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Kimmie', 'Everingham', 'keveringhamp@answers.com', '+966 244 570 3178', '402 Pepper Wood Lane', null, 'Al Muţayrifī', 'Saudi Arabia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Neall', 'Cantera', 'ncanteraq@statcounter.com', '+55 653 247 9474', '744 Pine View Terrace', '25600-000', 'Petrópolis', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Andria', 'Wainman', 'awainmanr@mozilla.com', '+86 846 720 0956', '1082 Bayside Place', null, 'Guyang', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Marshal', 'Layfield', 'mlayfields@bloomberg.com', '+55 248 473 5108', '80 Hooker Avenue', '77400-000', 'Gurupi', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Christopher', 'Rasper', 'craspert@reference.com', '+374 868 473 7071', '58280 School Park', null, 'Abovyan', 'Armenia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Kinna', 'Bleiman', 'kbleimanu@yandex.ru', '+61 408 660 9117', '52 Shasta Road', '8383', 'Melbourne', 'Australia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Demetria', 'Newgrosh', 'dnewgroshv@cocolog-nifty.com', '+262 700 913 6968', '2030 Arkansas Point', '97453 CEDEX', 'Saint-Pierre', 'Reunion');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Jenny', 'Loffhead', 'jloffheadw@uiuc.edu', '+258 719 358 9247', '17 Katie Court', null, 'Ilha de Moçambique', 'Mozambique');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Tillie', 'Gonsalvez', 'tgonsalvezx@berkeley.edu', '+48 400 869 7614', '3024 Schiller Park', '21-080', 'Garbów', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Haydon', 'Giovannilli', 'hgiovannilliy@51.la', '+385 698 659 5516', '49 Loomis Court', '33000', 'Virovitica', 'Croatia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Anica', 'Clineck', 'aclineckz@vimeo.com', '+1 593 239 1226', '910 Ilene Road', 'J2E', 'Drummondville', 'Canada');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Patsy', 'Peggram', 'ppeggram10@telegraph.co.uk', '+62 392 298 6885', '72731 Lakewood Junction', null, 'Liliana', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Killie', 'McGlone', 'kmcglone11@storify.com', '+62 539 917 0171', '61273 Larry Junction', null, 'Cimanggu', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Saidee', 'Dunphy', 'sdunphy12@slideshare.net', '+351 514 828 0570', '1 Dakota Place', '1685-141', 'Famões', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Denys', 'Railton', 'drailton13@home.pl', '+20 845 828 8280', '577 Harper Hill', null, 'Cairo', 'Egypt');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Tiphanie', 'Rosedale', 'trosedale14@examiner.com', '+60 246 346 8185', '1228 Helena Drive', '70690', 'Seremban', 'Malaysia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Eilis', 'Alwin', 'ealwin15@dell.com', '+49 861 367 7085', '4539 Bartelt Court', '44869', 'Bochum', 'Germany');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Gunter', 'Nazair', 'gnazair16@xinhuanet.com', '+963 693 629 2133', '35 Dovetail Park', null, 'Ash Shaddādah', 'Syria');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Eustacia', 'Dyet', 'edyet17@amazon.de', '+20 371 715 6542', '57 Sullivan Street', null, 'Akhmīm', 'Egypt');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Barthel', 'Ruddoch', 'bruddoch18@simplemachines.org', '+62 608 403 6008', '27423 Helena Place', null, 'Kertahayu', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Cammy', 'Fantham', 'cfantham19@jalbum.net', '+86 378 388 3487', '041 Dakota Place', null, 'Yanqian', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Shae', 'Bridgewood', 'sbridgewood1a@yahoo.com', '+256 164 349 7291', '9 Prairieview Alley', null, 'Kaliro', 'Uganda');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Susannah', 'Costley', 'scostley1b@engadget.com', '+380 362 423 6696', '17 Dapin Center', null, 'Alchevs’k', 'Ukraine');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Desiree', 'Clements', 'dclements1c@mayoclinic.com', '+86 426 578 5576', '60 Esch Parkway', null, 'Dalu', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ivar', 'Gatty', 'igatty1d@mayoclinic.com', '+351 981 318 0624', '0977 Jenna Court', '3400-498', 'Vendas de Galizes', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Dewey', 'Upcraft', 'dupcraft1e@networkadvertising.org', '+46 946 640 6492', '7196 Kipling Crossing', '911 32', 'Vännäs', 'Sweden');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ralph', 'Geistbeck', 'rgeistbeck1f@nbcnews.com', '+351 494 848 8036', '0 Little Fleur Center', '4620-031', 'Campos', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rutger', 'Botly', 'rbotly1g@behance.net', '+7 891 321 9375', '835 Northland Avenue', '214501', 'Smolensk', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Knox', 'Ness', 'kness1h@drupal.org', '+48 386 744 0705', '85567 Talmadge Court', '73-201', 'Choszczno', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rachele', 'Nolan', 'rnolan1i@comcast.net', '+86 656 147 5594', '44011 3rd Court', null, 'Yanling', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Claudius', 'Shovlar', 'cshovlar1j@bizjournals.com', '+86 532 519 6386', '68 Drewry Lane', null, 'Pangushan', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Lottie', 'Sellwood', 'lsellwood1k@aboutads.info', '+55 945 293 7124', '6053 Jackson Center', '13710-000', 'Tambaú', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Remy', 'Surmon', 'rsurmon1l@hugedomains.com', '+48 226 254 1152', '62 Blaine Crossing', '42-293', 'Kalej', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Mandel', 'Kettlewell', 'mkettlewell1m@shinystat.com', '+62 668 177 7024', '655 Di Loreto Point', null, 'Cipatat', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Amy', 'Callington', 'acallington1n@devhub.com', '+48 140 723 8331', '288 Graceland Court', '36-040', 'Boguchwała', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Nollie', 'Lahiff', 'nlahiff1o@51.la', '+503 258 247 6860', '539 Messerschmidt Road', null, 'Zacatecoluca', 'El Salvador');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Marrilee', 'Folland', 'mfolland1p@ask.com', '+386 752 618 7412', '8 Meadow Ridge Junction', '9261', 'Cankova', 'Slovenia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Olag', 'Esslement', 'oesslement1q@ft.com', '+351 594 909 0527', '524 Sutteridge Center', '3660-694', 'Várzea', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Saul', 'Chadwen', 'schadwen1r@cbsnews.com', '+62 933 310 4812', '5 Burrows Hill', null, 'Sukamahi Satu', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rodrigo', 'Kaley', 'rkaley1s@latimes.com', '+86 791 479 0644', '72 Banding Junction', null, 'Shishan', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Papagena', 'Smout', 'psmout1t@feedburner.com', '+51 608 898 2300', '200 Westport Crossing', null, 'Curibaya', 'Peru');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Vinson', 'Houldin', 'vhouldin1u@weebly.com', '+48 839 597 1145', '233 Del Sol Crossing', '33-160', 'Ryglice', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ibby', 'O'' Molan', 'iomolan1v@howstuffworks.com', '+34 259 487 1817', '004 New Castle Drive', '38110', 'Santa Cruz De Tenerife', 'Spain');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Mattie', 'Dilleway', 'mdilleway1w@51.la', '+46 266 674 5288', '231 Texas Plaza', '862 24', 'Kvissleby', 'Sweden');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Chickie', 'Groundwator', 'cgroundwator1x@canalblog.com', '+55 887 995 5134', '7983 Mesta Way', '63580-000', 'Jucás', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Abran', 'Verrillo', 'averrillo1y@facebook.com', '+86 303 986 6522', '2543 Towne Terrace', null, 'Dasongshu', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Louis', 'Cawte', 'lcawte1z@weebly.com', '+420 128 397 6597', '5 Blaine Park', '506 01', 'Liběšice', 'Czech Republic');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Guss', 'Brugman', 'gbrugman20@loc.gov', '+62 196 279 6817', '01 Kedzie Alley', null, 'Mekarsari', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Pavla', 'Bugler', 'pbugler21@simplemachines.org', '+62 473 936 4428', '3201 Pawling Trail', null, 'Jongorsari', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Hetty', 'McKinna', 'hmckinna22@bluehost.com', '+229 281 994 9641', '0 Northport Plaza', null, 'Tchaourou', 'Benin');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Fairlie', 'Sparshott', 'fsparshott23@shop-pro.jp', '+86 325 208 3518', '2 Evergreen Street', null, 'Shuanggang', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Sarette', 'Tibbetts', 'stibbetts24@tinypic.com', '+351 560 636 4506', '95 Heath Street', '2785-220', 'Mato Cheirinhos', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Leoline', 'Stelli', 'lstelli25@last.fm', '+49 704 165 2598', '67 Sycamore Pass', '76199', 'Karlsruhe', 'Germany');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Manolo', 'Ibell', 'mibell26@berkeley.edu', '+244 119 683 1519', '74 Brickson Park Point', null, 'N’dalatando', 'Angola');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Willette', 'Butchart', 'wbutchart27@hatena.ne.jp', '+57 108 664 1967', '963 Maryland Crossing', '051468', 'Liborina', 'Colombia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Chico', 'Scrimshire', 'cscrimshire28@lulu.com', '+86 453 367 6658', '8526 Ramsey Center', null, 'Huangshi', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Bryana', 'Mullins', 'bmullins29@nytimes.com', '+84 192 173 0613', '98 Express Terrace', null, 'Thị Trấn Tủa Chùa', 'Vietnam');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Bat', 'Matevosian', 'bmatevosian2a@foxnews.com', '+86 269 764 5288', '4084 Pennsylvania Crossing', null, 'Gaomi', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Paulette', 'Torbeck', 'ptorbeck2b@utexas.edu', '+84 229 700 9275', '6 Lerdahl Court', null, 'Thị Trấn Than Uyên', 'Vietnam');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Minerva', 'Wreiford', 'mwreiford2c@mac.com', '+86 694 792 2224', '16 Pawling Junction', null, 'Beizheng', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Yelena', 'Canero', 'ycanero2d@yale.edu', '+81 325 836 5686', '84 Buell Trail', '905-0002', 'Katsuyama', 'Japan');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Mano', 'Dudderidge', 'mdudderidge2e@php.net', '+54 168 505 3603', '430 Gina Terrace', '3412', 'Chilecito', 'Argentina');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Carena', 'Larkins', 'clarkins2f@utexas.edu', '+57 413 533 1368', '16638 Green Ridge Center', '686508', 'Betulia', 'Colombia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Marni', 'Flaws', 'mflaws2g@last.fm', '+385 407 291 1527', '57 Barby Lane', '48322', 'Drnje', 'Croatia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Cathy', 'Sinkin', 'csinkin2h@cnet.com', '+225 655 355 5967', '44574 Bunker Hill Pass', null, 'Agboville', 'Ivory Coast');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Eloisa', 'Haskayne', 'ehaskayne2i@blogger.com', '+7 512 447 2372', '4373 Aberg Circle', '143015', 'Novo-Peredelkino', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Margret', 'Sharkey', 'msharkey2j@wikimedia.org', '+86 465 130 3541', '1862 Ridgeway Pass', null, 'Huangzhawan', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Jorey', 'Pine', 'jpine2k@bing.com', '+261 582 251 3531', '43152 Roth Way', null, 'Antsohihy', 'Madagascar');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Marabel', 'De Gogay', 'mdegogay2l@washingtonpost.com', '+84 950 730 6137', '86 Eagan Street', null, 'Bồng Sơn', 'Vietnam');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Corie', 'Giacopetti', 'cgiacopetti2m@weibo.com', '+33 783 444 4764', '43170 Claremont Court', '66019 CEDEX 9', 'Perpignan', 'France');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Jaynell', 'Garrals', 'jgarrals2n@networkadvertising.org', '+62 970 201 3681', '819 Novick Terrace', null, 'Besuki Dua', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Honey', 'Bailles', 'hbailles2o@washingtonpost.com', '+48 129 955 9517', '80 Declaration Alley', '87-730', 'Nieszawa', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Glendon', 'Ginn', 'gginn2p@google.es', '+86 707 339 2286', '6 Green Ridge Drive', null, 'Shanghu', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Silvain', 'Randals', 'srandals2q@seattletimes.com', '+62 265 132 9185', '7 Thierer Park', null, 'Marisgama', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Goldia', 'Espino', 'gespino2r@smh.com.au', '+62 390 305 9974', '0684 Pankratz Junction', null, 'Sapeken', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Erminia', 'Vella', 'evella2s@who.int', '+62 977 875 3145', '2 Michigan Crossing', null, 'Baratleke', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Debi', 'Kedslie', 'dkedslie2t@ustream.tv', '+86 919 843 8775', '6 Blaine Avenue', null, 'Chengjiao', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Evaleen', 'Yurkov', 'eyurkov2u@ted.com', '+380 788 166 4070', '12 Erie Circle', null, 'Chapayevka', 'Ukraine');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Stanwood', 'Round', 'sround2v@woothemes.com', '+63 411 731 4703', '2489 Summerview Avenue', '4501', 'Pawa', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Raphaela', 'Dingley', 'rdingley2w@issuu.com', '+46 386 684 1855', '01041 7th Plaza', '331 29', 'Värnamo', 'Sweden');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Katharyn', 'Rubartelli', 'krubartelli2x@altervista.org', '+62 484 979 4756', '620 Bultman Trail', null, 'Sila', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Betsy', 'Cowderoy', 'bcowderoy2y@goo.gl', '+7 561 165 9726', '1745 4th Way', '403793', 'Zhirnovsk', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ollie', 'Boules', 'oboules2z@marketwatch.com', '+351 781 858 8140', '49 School Trail', '4815-075', 'Ínfias', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ginelle', 'Coull', 'gcoull30@nydailynews.com', '+51 488 308 9392', '5 Porter Avenue', null, 'Morropón', 'Peru');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Lilyan', 'Marchbank', 'lmarchbank31@live.com', '+420 116 932 4635', '31998 Melvin Avenue', '687 11', 'Topolná', 'Czech Republic');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Merilyn', 'Cowsby', 'mcowsby32@ebay.co.uk', '+86 193 151 0844', '41 Golf Course Plaza', null, 'Qingtong', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Maurise', 'Grimestone', 'mgrimestone33@ihg.com', '+62 699 833 2505', '2 Burrows Hill', null, 'Jiwuwu', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Alayne', 'Burnyeat', 'aburnyeat34@disqus.com', '+267 849 396 5061', '3 Westerfield Terrace', null, 'Gaborone', 'Botswana');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Jill', 'Rossbrooke', 'jrossbrooke35@ameblo.jp', '+86 945 543 7244', '93 Buell Circle', null, 'Liuhe', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rakel', 'Helliwell', 'rhelliwell36@yolasite.com', '+1 904 598 8788', '8065 Tomscot Junction', '32204', 'Jacksonville', 'United States');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Roda', 'Thurman', 'rthurman37@yellowbook.com', '+63 644 599 5191', '6103 Merry Plaza', '5702', 'Aurelliana', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Chariot', 'Scammonden', 'cscammonden38@ox.ac.uk', '+66 335 537 0047', '1 Thierer Place', '36190', 'Rattanawapi', 'Thailand');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Odette', 'Baldam', 'obaldam39@oaic.gov.au', '+52 560 333 9024', '064 Kensington Circle', '29950', 'San Sebastian', 'Mexico');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Jonell', 'Villiers', 'jvilliers3a@about.me', '+62 296 756 4855', '70623 South Parkway', null, 'Ladoang', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ignaz', 'Olliffe', 'iolliffe3b@cbsnews.com', '+7 786 925 7597', '26 Swallow Plaza', '623075', 'Gadzhiyevo', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Jordan', 'Nicklinson', 'jnicklinson3c@people.com.cn', '+7 686 139 2006', '71106 Hansons Avenue', '646760', 'Pavlogradka', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Butch', 'Torri', 'btorri3d@w3.org', '+86 830 759 7869', '3 Hooker Pass', null, 'Duogongma', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rachael', 'Coogan', 'rcoogan3e@amazonaws.com', '+33 154 967 6239', '01 Pennsylvania Plaza', '67039 CEDEX 2', 'Strasbourg', 'France');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Tillie', 'Sunman', 'tsunman3f@yellowpages.com', '+57 543 545 9712', '699 Florence Center', '684058', 'Galán', 'Colombia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Andreas', 'Kenforth', 'akenforth3g@dedecms.com', '+420 433 513 9502', '6 Valley Edge Road', '257 22', 'Čerčany', 'Czech Republic');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Valentijn', 'Roscoe', 'vroscoe3h@github.com', '+86 642 701 6732', '9 Rowland Avenue', null, 'Chenfang', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Lynnell', 'Smurfitt', 'lsmurfitt3i@shinystat.com', '+62 535 353 2350', '301 Green Place', null, 'Suwaduk', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Bryon', 'McMullen', 'bmcmullen3j@sun.com', '+86 285 526 9097', '31402 Sugar Drive', null, 'Yangji', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Federica', 'Bracknell', 'fbracknell3k@illinois.edu', '+62 861 658 6215', '4 Ruskin Junction', null, 'Lailunggi', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Teri', 'Roundtree', 'troundtree3l@nasa.gov', '+84 463 390 4749', '517 Farmco Way', null, 'Quận Tân Phú', 'Vietnam');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Sidnee', 'Meddows', 'smeddows3m@istockphoto.com', '+82 667 232 9196', '158 Vidon Junction', null, 'Nonsan', 'South Korea');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Hastie', 'Codi', 'hcodi3n@studiopress.com', '+86 495 796 6188', '512 Dexter Hill', null, 'Dayu', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('George', 'Wardlow', 'gwardlow3o@prlog.org', '+63 586 838 5223', '80 Kropf Park', '2437', 'Palguyod', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ortensia', 'Lauderdale', 'olauderdale3p@illinois.edu', '+57 341 222 6284', '68 Farragut Center', '151287', 'El Cocuy', 'Colombia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Gianina', 'Praundl', 'gpraundl3q@imageshack.us', '+63 548 616 1174', '0 Russell Place', '1930', 'Angono', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Kippy', 'Worlidge', 'kworlidge3r@rambler.ru', '+86 190 917 2568', '7223 Carioca Parkway', null, 'Zhaoxiang', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Gerri', 'Grollmann', 'ggrollmann3s@skyrock.com', '+63 470 159 1444', '0 Novick Road', '6534', 'Labnig', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Adelbert', 'Karolowski', 'akarolowski3t@harvard.edu', '+57 314 447 5328', '52887 Burrows Trail', '732068', 'Guayabal', 'Colombia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Joice', 'Ibbison', 'jibbison3u@cnn.com', '+93 684 745 7129', '3763 Morningstar Parkway', null, 'Qarchī Gak', 'Afghanistan');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ferguson', 'Flaune', 'fflaune3v@g.co', '+48 857 885 0901', '51 Surrey Crossing', '06-121', 'Pokrzywnica', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Katlin', 'Krug', 'kkrug3w@bigcartel.com', '+54 483 395 5621', '2 Surrey Lane', '3733', 'Chorotis', 'Argentina');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Shel', 'Andreou', 'sandreou3x@constantcontact.com', '+7 779 358 0522', '7461 Fairview Drive', '416457', 'Nachalovo', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Leland', 'Rault', 'lrault3y@usda.gov', '+86 778 374 9381', '845 Dorton Alley', null, 'Zengjia', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Brion', 'Yekel', 'byekel3z@opera.com', '+220 787 805 2967', '25 Holy Cross Road', null, 'Karantaba', 'Gambia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Dorree', 'Spare', 'dspare40@sbwire.com', '+245 188 503 5897', '91 Union Center', null, 'Bissau', 'Guinea-Bissau');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Andriette', 'Aldred', 'aaldred41@about.com', '+62 477 384 9928', '76025 3rd Trail', null, 'Rukunlima Bawah', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Aigneis', 'Vanyatin', 'avanyatin42@ftc.gov', '+55 213 133 8249', '3945 Steensland Road', '86360-000', 'Bandeirantes', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Munroe', 'Mettetal', 'mmettetal43@nyu.edu', '+63 757 583 2269', '09109 Montana Court', '8112', 'Santo Tomas', 'Philippines');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Diandra', 'Reicharz', 'dreicharz44@freewebs.com', '+352 845 693 8037', '61 Clarendon Pass', 'L-8273', 'Mamer', 'Luxembourg');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ursula', 'Hanster', 'uhanster45@admin.ch', '+234 636 832 5295', '65 6th Hill', null, 'Kaduna', 'Nigeria');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Arden', 'Rubinshtein', 'arubinshtein46@utexas.edu', '+380 705 864 2827', '2178 Dahle Alley', null, 'Volodars’k-Volyns’kyy', 'Ukraine');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Dillon', 'Ferrer', 'dferrer47@msu.edu', '+1 233 853 3500', '28729 Canary Drive', 'H9K', 'Sainte-Marthe-sur-le-Lac', 'Canada');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rikki', 'Noot', 'rnoot48@t-online.de', '+86 211 124 1097', '64 Dapin Park', null, 'Zhoutie', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Bianka', 'Gothrup', 'bgothrup49@godaddy.com', '+64 541 187 4090', '366 Orin Road', '0794', 'Rothesay Bay', 'New Zealand');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Tillie', 'Juckes', 'tjuckes4a@psu.edu', '+351 498 413 5758', '76071 5th Junction', '3100-806', 'Casais', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Odella', 'Siccombe', 'osiccombe4b@chicagotribune.com', '+386 837 508 1081', '2405 Merrick Junction', '1357', 'Notranje Gorice', 'Slovenia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Garreth', 'Truman', 'gtruman4c@domainmarket.com', '+1 814 860 5201', '43245 Graceland Avenue', '11003', 'Hato Mayor del Rey', 'Dominican Republic');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Gwendolin', 'Jenking', 'gjenking4d@livejournal.com', '+420 190 913 0185', '7044 Corscot Parkway', '735 72', 'Petrovice u Karviné', 'Czech Republic');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Barry', 'Luca', 'bluca4e@soup.io', '+62 165 995 1547', '51 Hayes Hill', null, 'Muara Sabak', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Dolorita', 'Graddon', 'dgraddon4f@rediff.com', '+86 585 179 2407', '48783 Portage Way', null, 'Hanjia', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Lou', 'Rilton', 'lrilton4g@cargocollective.com', '+51 204 248 5473', '6 Manley Plaza', null, 'Huancabamba', 'Peru');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Abran', 'McCane', 'amccane4h@joomla.org', '+86 847 788 7557', '4481 Prairieview Point', null, 'Cezi', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Janaya', 'Chree', 'jchree4i@chronoengine.com', '+86 136 342 3884', '9791 Arizona Lane', null, 'Jieshou', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ian', 'Esom', 'iesom4j@marketwatch.com', '+55 577 669 9093', '9907 Anhalt Terrace', '32500-000', 'Betim', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Ebba', 'Monery', 'emonery4k@a8.net', '+351 955 966 2271', '41998 Dayton Street', '9700-685', 'Terra Chã', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Eileen', 'Whitbread', 'ewhitbread4l@nasa.gov', '+48 686 317 4537', '50798 Canary Trail', '83-010', 'Kowale', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Eimile', 'Scothern', 'escothern4m@behance.net', '+81 456 957 4364', '65913 Montana Trail', '319-1559', 'Kitaibaraki', 'Japan');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rolf', 'Critch', 'rcritch4n@photobucket.com', '+86 345 812 8838', '5 Pond Junction', null, 'Zhuxi', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Mellicent', 'McCard', 'mmccard4o@amazon.de', '+7 511 846 4374', '8848 Brickson Park Terrace', '601554', 'Urshel’skiy', 'Russia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Matthew', 'Adanet', 'madanet4p@liveinternet.ru', '+86 106 337 1902', '40929 Main Circle', null, 'Dahewan', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Nonah', 'Paolozzi', 'npaolozzi4q@wiley.com', '+55 611 469 6257', '2 Browning Point', '19700-000', 'Paraguaçu Paulista', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Mayne', 'De Benedetti', 'mdebenedetti4r@desdev.cn', '+62 819 515 1345', '04 Knutson Pass', null, 'Dukuhsawah', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Marc', 'Pilling', 'mpilling4s@prweb.com', '+54 573 889 4048', '360 Fordem Court', '5311', 'Arauco', 'Argentina');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Melonie', 'Amey', 'mamey4t@cpanel.net', '+358 419 678 9197', '617 Hoepker Parkway', '89201', 'Puolanka', 'Finland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Johannah', 'Scurrah', 'jscurrah4u@people.com.cn', '+359 168 654 7818', '61407 Summerview Parkway', '6200', 'Chirpan', 'Bulgaria');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Clemmy', 'Tong', 'ctong4v@sbwire.com', '+351 499 602 5975', '7 Lakewood Way', '4620-472', 'Venda', 'Portugal');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Stanley', 'Swanborrow', 'sswanborrow4w@rediff.com', '+355 708 650 0030', '223 Rowland Drive', null, 'Iballë', 'Albania');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Vasily', 'Tearny', 'vtearny4x@gizmodo.com', '+56 101 861 1334', '7761 Raven Trail', null, 'Santiago', 'Chile');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Kerrie', 'Hammett', 'khammett4y@sakura.ne.jp', '+86 681 410 6688', '42927 Crescent Oaks Center', null, 'Hejiadong', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Bill', 'O''Curneen', 'bocurneen4z@who.int', '+380 717 440 6112', '385 Manufacturers Parkway', null, 'Nizhyn', 'Ukraine');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Coretta', 'Ferrino', 'cferrino50@1688.com', '+1 403 584 4990', '10 Springview Trail', 'C1B', 'Charlottetown', 'Canada');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Cris', 'Uman', 'cuman51@zdnet.com', '+86 958 222 9043', '55813 Oneill Alley', null, 'Tangba', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rosalind', 'Scales', 'rscales52@google.pl', '+62 831 904 3615', '12434 Briar Crest Way', null, 'Bedadung Kulon', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Paige', 'Rippon', 'prippon53@taobao.com', '+55 482 385 2632', '22027 Gerald Plaza', '62640-000', 'Pentecoste', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Yorgo', 'Outerbridge', 'youterbridge54@mlb.com', '+81 643 573 5700', '0 Magdeline Court', '729-5122', 'Kushiro', 'Japan');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Rocky', 'Bunten', 'rbunten55@amazon.co.uk', '+389 313 380 5126', '72317 Dryden Road', '1221', 'Kamenjane', 'Macedonia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Wesley', 'Deadman', 'wdeadman56@facebook.com', '+86 265 952 2010', '51 Jana Junction', null, 'Limushan', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Aksel', 'Gant', 'agant57@geocities.com', '+81 430 734 4919', '2182 Carioca Lane', '807-0133', 'Ashiya', 'Japan');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Igor', 'Greeno', 'igreeno58@dedecms.com', '+62 718 156 5874', '08536 Paget Junction', null, 'Gununglajang', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Allen', 'Gaynesford', 'agaynesford59@ucoz.ru', '+86 219 669 8323', '6929 Oriole Junction', null, 'Xindian', 'China');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Hakeem', 'Klazenga', 'hklazenga5a@nih.gov', '+62 504 613 9391', '26 Maryland Circle', null, 'Paritjunus', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Grantley', 'Gull', 'ggull5b@bloomberg.com', '+51 137 571 9135', '9 Old Shore Hill', null, 'Mollepampa', 'Peru');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Sid', 'Limbert', 'slimbert5c@uiuc.edu', '+33 764 818 4436', '6 Mccormick Avenue', '64044 CEDEX', 'Pau', 'France');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Vasily', 'Miskimmon', 'vmiskimmon5d@who.int', '+48 984 413 1746', '491 Randy Crossing', '44-370', 'Szczerbice', 'Poland');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Zollie', 'Dimitrescu', 'zdimitrescu5e@princeton.edu', '+55 852 312 8609', '791 Memorial Place', '88750-000', 'Braço do Norte', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Halley', 'Holtum', 'hholtum5f@so-net.ne.jp', '+507 803 644 2104', '28 Banding Plaza', null, 'Llano Largo', 'Panama');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Peter', 'Buncombe', 'pbuncombe5g@yellowbook.com', '+62 660 108 9263', '2 Russell Plaza', null, 'Sukowiryo', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Paquito', 'Croizier', 'pcroizier5h@mediafire.com', '+55 875 433 8964', '1212 Harbort Place', '58750-000', 'Juru', 'Brazil');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Victoir', 'Baumann', 'vbaumann5i@usatoday.com', '+62 243 155 4635', '4 Thompson Trail', null, 'Banjar Medura', 'Indonesia');
insert into Customer (first_name, last_name, email, phone_number, street_address, postal_code, city, country) values ('Delila', 'Kenrick', 'dkenrick5j@storify.com', '+7 211 432 3010', '18423 Eliot Avenue', '184021', 'Zelenoborskiy', 'Russia');
=======


-- Kreditkort
INSERT INTO creditcard (card_type) VALUES ('American Express');
INSERT INTO creditcard (card_type) VALUES ('Bankcard');
INSERT INTO creditcard (card_type) VALUES ('Diners Club');
INSERT INTO creditcard (card_type) VALUES ('InstaPayment');
INSERT INTO creditcard (card_type) VALUES ('JCB');
INSERT INTO creditcard (card_type) VALUES ('Laser');
INSERT INTO creditcard (card_type) VALUES ('Mastercard');
INSERT INTO creditcard (card_type) VALUES ('Mestro');
INSERT INTO creditcard (card_type) VALUES ('Solo');
INSERT INTO creditcard (card_type) VALUES ('Switch');
INSERT INTO creditcard (card_type) VALUES ('Visa');
GO



=======
insert into discount (discount_code, discount_amount) values ('Summer20', 20);
insert into discount (discount_code, discount_amount) values ('Autumn20', 20);
insert into discount (discount_code, discount_amount) values ('Spring20', 20);
insert into discount (discount_code, discount_amount) values ('Winter20', 20);
insert into discount (discount_code, discount_amount) values ('Birthday10', 10);
insert into discount (discount_code, discount_amount) values ('Employe50', 50);
insert into discount (discount_code, discount_amount) values ('Weekend15', 15);
insert into discount (discount_code, discount_amount) values ('Company5', 5);
insert into discount (discount_code, discount_amount) values ('Owner100', 100);
insert into discount (discount_code, discount_amount) values ('Superdeal50', 50);
>>>>>>> 44e88601db739ee6fc47d73aa7436e92828b0e5b

